[workspace]
members = [
    "coordinator",
    "endorser",
    "ledger",
    "store",
    "endpoint",
    "endpoint_rest",
    "light_client_rest",
    "coordinator_ctrl",
]

resolver = "3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
